//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.CompanyStaffs = new HashSet<CompanyStaff>();
            this.TrainingRecords = new HashSet<TrainingRecord>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int EmployeeID { get; set; }
        public string EmpCode { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> AuthenDomain { get; set; }
        public string Email { get; set; }
        public string DomainName { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string TitleEn { get; set; }
        public string FirstNameEn { get; set; }
        public string MidNameEn { get; set; }
        public string LastNameEn { get; set; }
        public string TitleTh { get; set; }
        public string FirstNameTh { get; set; }
        public string MidNameTh { get; set; }
        public string LastNameTh { get; set; }
        public string CitizenID { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string PositionNameEn { get; set; }
        public string PositionNameTh { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CompanyStaff> CompanyStaffs { get; set; }
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<TrainingRecord> TrainingRecords { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
