//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> MenuOrder { get; set; }
    }
}
