//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingRecord
    {
        public int TrainingRecordID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TrainingCourseID { get; set; }
        public string Trainer { get; set; }
        public string Organized { get; set; }
        public System.DateTime TrainingStartDate { get; set; }
        public System.DateTime TrainingEndDate { get; set; }
        public string Venue { get; set; }
        public string CertificateHESInduction { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string FollowUpSSE { get; set; }
        public string MonthOfCompletionSSE { get; set; }
        public string YearOfCompletionSSE { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
        public virtual TrainingCourse TrainingCourse { get; set; }
    }
}
